---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendemo-deployment
  labels:
    app: opendemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendemo
  template:
    metadata:
      labels:
        app: opendemo
    spec:
      containers:
      - name: opendemo
        image: debuggerboy/sshserver:0.0.2
        ports:
        - containerPort: 22
        volumeMounts:
        - name: authorized-keys-volume
          mountPath: /home/anish/.ssh
        env:
        - name: "UID"
          value: "1001"
        - name: "GID"
          value: "1001"
        - name: "USER"
          value: "cdev1"
      volumes:
        - name: authorized-keys-volume
          configMap:
            name: ssh-auth-key
---
apiVersion: v1
kind: Service
metadata:
  name: opendemo-service
  labels:
    app: opendemo
spec:
  type: LoadBalancer
  ports:
  - port: 22
  selector:
    app: opendemo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-auth-key
data:
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA0FwmMBdxp66qOWRXGIZQio0nfvqKfiSZ/+90CEz8I52bh5ajIEboTgHr26591sAEulg7FK2d847lvib1X6Teddui+QkUQwEKHFXY+D+vDntdYJeBCg+yPA+gxzFZ0zWQVXsCbIZNIKpnR6X6/SAOXMkXpOaMAtfd7faAOSOOBLgc/v9wolSlDLdZt67SuuJf6c44dPFqAwVeE4h6hsoqWnCOeH8wFMl7UWZFgMa9tmXAUpB4rlCcDKjr4Dp92VlB7PJHdGypjpyT9n4Cy/LNmeVLO+udejNSWDkachqZxZW7Nbwqx1jCpSgLnX/wr2qbJyxfSXhNxUw2aneisNlD/Q==
